apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-python
  template:
    metadata:
      labels:
        app: web-python
    spec:
      containers:
        - name: web-python
          image: kerthik087/web-python:v1.3
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-python-service
spec:
  selector:
    app: web-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

  