apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: 'git@github.com:kerthik/Files.git' 
    path: python
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
